export enum DatabaseToken {
    AUTH_SERVICE = "AUTH_SERVICE",
    LOBBY_ADAPTER = "LOBBY_ADAPTER",
    LOBBY_SERVICE = "LOBBY_SERVICE",
    LOBBY_USER_ADAPTER = "LOBBY_USER_ADAPTER",
    LOBBY_USER_SERVICE = "LOBBY_USER_SERVICE",
    USER_ADAPTER = "USER_ADAPTER",
    USER_SERVICE = "USER_SERVICE",
}